# Generated by Django 3.2.2 on 2021-07-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/%y/%m/%d'),
        ),
    ]
