# Generated by Django 3.2.2 on 2021-07-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_logs_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='lesson_num',
        ),
    ]
