# Generated by Django 3.2.2 on 2021-07-03 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('teacher', models.ForeignKey(db_column='teacher', on_delete=django.db.models.deletion.CASCADE, related_name='courses_teacher_offline', to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, related_name='group_courses', to='Offline.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^(010|011|012|015)[0-9]{8}$', message='رقم الهاتف يجب ان يبدا ب 011 او 012 او 010 او 015 و يجب ان يكون مكون من 11 رقم')])),
                ('parent_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^(010|011|012|015)[0-9]{8}$', message='رقم الهاتف يجب ان يبدا ب 011 او 012 او 010 او 015 و يجب ان يكون مكون من 11 رقم')])),
            ],
        ),
        migrations.CreateModel(
            name='Student_courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, related_name='student_courses_courses', to='Offline.courses')),
                ('group', models.ForeignKey(db_column='group', on_delete=django.db.models.deletion.CASCADE, related_name='student_courses_groups', to='Offline.groups')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, related_name='student_courses_students', to='Offline.students')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, related_name='sessions_courses', to='Offline.courses')),
                ('group', models.ForeignKey(db_column='sessions_groups', on_delete=django.db.models.deletion.CASCADE, to='Offline.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Session_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.BooleanField(default=False)),
                ('home_work', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=False)),
                ('session', models.ForeignKey(db_column='session', on_delete=django.db.models.deletion.CASCADE, related_name='session_data_sessions', to='Offline.sessions')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, related_name='session_data_students', to='Offline.students')),
            ],
        ),
        migrations.AddIndex(
            model_name='student_courses',
            index=models.Index(fields=['course'], name='IX_Student_courses'),
        ),
        migrations.AlterUniqueTogether(
            name='student_courses',
            unique_together={('group_id', 'code')},
        ),
        migrations.AddIndex(
            model_name='session_data',
            index=models.Index(fields=['session'], name='IX_Session_data_session'),
        ),
        migrations.AlterUniqueTogether(
            name='session_data',
            unique_together={('session', 'student')},
        ),
    ]
