# Generated by Django 3.2.2 on 2021-07-03 18:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='courses/%y/%m/%d')),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(db_column='teacher', on_delete=django.db.models.deletion.CASCADE, related_name='courses_teachers', to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, related_name='student_courses_courses', to='Courses.courses')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, related_name='student_courses_students', to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, related_name='requests_students', to='Courses.courses')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, related_name='requests_students', to='users.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='student_courses',
            index=models.Index(fields=['student'], name='IX_Student_courses_student'),
        ),
        migrations.AddIndex(
            model_name='student_courses',
            index=models.Index(fields=['course'], name='IX_Student_courses_courses'),
        ),
        migrations.AlterUniqueTogether(
            name='student_courses',
            unique_together={('course', 'student')},
        ),
        migrations.AddIndex(
            model_name='requests',
            index=models.Index(fields=['course'], name='IX_Requests'),
        ),
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together={('course', 'student')},
        ),
    ]
