# Generated by Django 3.2.2 on 2021-07-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_courses',
            name='group',
            field=models.ForeignKey(db_column='group', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_courses_groups', to='Groups.groups'),
        ),
    ]
