# Generated by Django 3.2.2 on 2021-07-05 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
        ('Courses', '0002_student_courses_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_courses',
            name='group',
            field=models.ForeignKey(blank=True, db_column='group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_courses_groups', to='Groups.groups'),
        ),
    ]
