# Generated by Django 3.2.2 on 2021-07-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_student_courses_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_courses',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
