# Generated by Django 3.2.2 on 2021-07-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_alter_courses_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.CharField(blank=True, choices=[('علمى', 'علمى'), ('ادبي', 'ادبي'), ('الجميع', 'الجميع')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='lesson_num',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
