# Generated by Django 3.2.2 on 2021-07-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Groups', '0001_initial'),
        ('users', '0001_initial'),
        ('Questions', '__first__'),
        ('Courses', '0002_student_courses_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('Limit', models.TimeField()),
                ('description', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=25)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_courses', to='Courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('results', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(db_column='exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results_exams', to='Exams.exams')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results_students', to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(db_column='exam', on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Exams.exams')),
                ('question', models.ForeignKey(db_column='question', on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions_questions', to='Questions.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam', models.ForeignKey(db_column='exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_groups_exams', to='Exams.exams')),
                ('group', models.ForeignKey(db_column='group', on_delete=django.db.models.deletion.CASCADE, related_name='exam_groups_groups', to='Groups.groups')),
            ],
        ),
        migrations.AddIndex(
            model_name='exams',
            index=models.Index(fields=['course'], name='IX_Exams'),
        ),
        migrations.AddIndex(
            model_name='exam_results',
            index=models.Index(fields=['exam'], name='IX_Exam_results'),
        ),
        migrations.AddIndex(
            model_name='exam_questions',
            index=models.Index(fields=['exam'], name='IX_Exam_questions'),
        ),
        migrations.AlterUniqueTogether(
            name='exam_questions',
            unique_together={('exam', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='exam_groups',
            unique_together={('exam', 'group')},
        ),
    ]
