# Generated by Django 3.2.2 on 2021-07-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0002_alter_lessons_source'),
        ('Exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='lesson',
            field=models.ForeignKey(blank=True, db_column='lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exam_lessons', to='Lessons.lessons'),
        ),
    ]
