# Generated by Django 3.2.2 on 2021-07-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
