# Generated by Django 3.2.2 on 2021-07-03 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('Courses', '0002_student_courses_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isMultiple', models.BooleanField()),
                ('isTrueFalse', models.BooleanField()),
                ('content', models.CharField(max_length=455)),
                ('degree', models.PositiveSmallIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='questions/%y/%m/%d')),
                ('course', models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, related_name='questions_courses', to='Courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Wrong_answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(max_length=50)),
                ('question', models.ForeignKey(db_column='question', on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answers_questions', to='Questions.questions')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answers_students', to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Question_answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=70)),
                ('question', models.ForeignKey(db_column='question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='Questions.questions')),
            ],
        ),
        migrations.AddIndex(
            model_name='wrong_answers',
            index=models.Index(fields=['question'], name='IX_wrong_answers'),
        ),
        migrations.AlterUniqueTogether(
            name='wrong_answers',
            unique_together={('student', 'question')},
        ),
        migrations.AddIndex(
            model_name='questions',
            index=models.Index(fields=['course'], name='IX_Questions'),
        ),
        migrations.AddIndex(
            model_name='question_answers',
            index=models.Index(fields=['question'], name='IX_Question_answers'),
        ),
    ]
