# Generated by Django 3.2.2 on 2021-07-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrong_answers',
            name='selected_answer',
            field=models.ForeignKey(db_column='selected_answer', on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answers_selected_answer', to='Questions.question_answers'),
        ),
    ]
